### PR TITLE
[FIX] odoo-shippable: Install g++4.9 for new requirements of youcompleteme

### PR DESCRIPTION
**Pull request by JesusZapata**
The new version of youcompleteme require g++-4.9 instead of g++-4.8 https://github.com/Valloric/YouCompleteMe/commit/b20809332c3298cb954cff20006cb52955b54b2d#diff-354f30a63fb0907d4ad57269548329e3L37

This PR adding new ppa for install the version 4.9 of g++

Currently when I made one build of odoo-shippable show the following error

image

Fix https://github.com/Vauxoo/docker-odoo-image/issues/236

### CODE REVIEW

**Comment by JesusZapata** [comment]
@moylop260 @ruiztulio 
What would be the impact of changing the g ++, cpp and gcc version ?

**Comment by JesusZapata** [comment]
Travis is red for an isolated case https://travis-ci.org/Vauxoo/docker-odoo-image/builds/240881952#L3204

**Comment by ruiztulio** [comment]
@JesusZapata did you have any issue with the dependencies that need to be compiled? because that could be the only issue with this change

**Comment by JesusZapata** [comment]
@ruiztulio Thanks
@moylop260 
Are you agree this change ?

Travis is red for an isolated case
https://travis-ci.org/Vauxoo/docker-odoo-image/builds/240963962#L5437

**Comment by moylop260** [comment]
There is a way to get compiled the package `youcompleteme`
I don't like to install other compilers just for this low priority package

**Comment by JesusZapata** [comment]
@moylop260 
I try to find the compiled of `youcompleteme` but only found .deb packages

The .deb packages is not easy to install isolated, because this can be produce the break of apt-get

**Comment by moylop260** [comment]
Could you disable this plugin by default for now, please?

**Comment by JesusZapata** [comment]
@moylop260 
In this another pull request https://github.com/Vauxoo/docker-odoo-image/pull/242 for default you completeme is deactivated

**Pull request closed without merging**
