### PR TITLE
Install coverage in the virtual environment

### PR DESCRIPTION
**Pull request by mapuerta**
This PR resolves fix https://github.com/Vauxoo/odoo-peru/issues/70

### CODE REVIEW

**Comment by mapuerta** [comment]
@moylop260 @ruiztulio @JesusZapata Ready for review

I tried these changes with this [script](https://gist.github.com/mapuerta/dddfec199a7f10639592cd0bd51192bb)
Usage
**./testin_pr.sh -r git@github.com:Vauxoo/odoo-peru.git -b 10.0 -o true**
done_result

**Comment by JesusZapata** [comment]
@mapuerta @moylop260 @ruiztulio 
I ran locally this [script](https://gist.github.com/JesusZapata/6e49e804367f730f2e9586135ee62631) with the following parameter

`./testing_.sh -r git@github.com:Vauxoo/odoo-peru.git -b 10.0 -o true`

And it worked

captura de pantalla_2017-02-26_12-34-56

**Comment by moylop260** [comment]
@mapuerta 
This is working but I didn't understand why was failing and why this change fixed it

Could you add a conclusion comment here, please?

**Comment by moylop260** [comment]
FYI I have created the following patch
https://github.com/Vauxoo/travis2docker/pull/95
I think this was the real fix.

**Comment by mapuerta** [comment]
@moylop260 

The problem is that when the entrypoint.sh is executed when entering the container it executes the binary of the coverage of normal path and not of the virtualenv. What causes the normal python binary to run and ignoring all the libraries installed in the virtualenv

**Pull request merged**
