### PR TITLE
[FIX] Remove all odoo requirements from the full_requirements files.

### LINKED ISSUE #250: Use original odoo/requirements.txt to install packages
@ruiztulio We have created a PR in order to use the original odoo/requirements.txt:
 - https://github.com/OCA/maintainer-quality-tools/pull/455

We could use a similar behaviour to build the images.

(Could you re-assign it, please?)

### PR DESCRIPTION
**Pull request by ruiztulio**
so we can allow the processes that installs the requirements.txt do their job instead of having these wired ones.

@moylop260 all dependencies from odoo requirements.txt removed

Closes #250

### CODE REVIEW

**Comment by moylop260** [comment]
Do you have planned install from "wget https://raw.githubusercontent.com/odoo/odoo/10.0/requirements.txt && pip install -r requirements.txt" or Is not need it?

**Comment by ruiztulio** [comment]
@moylop260 As mentioned [here](https://github.com/Vauxoo/docker-odoo-image/pull/251#issuecomment-314189837) the [odoo repo is cloned](https://github.com/Vauxoo/docker-odoo-image/blob/master/odoo100/scripts/build-image.sh#L16-L19) there and all dependencies are installed from the Odoo requirements file. 

And just to be sure if something changed between the image build and the moment when we deploy an instance they are installed again [here](https://git.vauxoo.com/vauxoo/deployv/blob/master/deployv/templates/files/install_deps.py#L39) (updating if needed)

**Comment by moylop260** [comment]
Is unrelated the runbot red?
https://travis-ci.org/Vauxoo/docker-odoo-image/builds/252080349#L3387

`TypeError: super() argument 1 must be type, not None`

**Comment by ruiztulio** [comment]
@moylop260 yes, we have that error from 2 months ago (in the 10.0 and 9.0 images too):

a

But I wanted to update the images before, I'm trying to fix that error too (I'll push the solution when is ready in other PR if you are ok with that)

**Pull request merged**
