### PR TITLE
Master git completion truiz

### PR DESCRIPTION
**Pull request by ruiztulio**
@moylop260 this installs bash-completion package that is used in bash completion as you requested, but this will be available in all containers build from now on and all users

### CODE REVIEW

**Comment by nhomar** [comment]
:+1:

**Comment by moylop260** [comment]
:+1:

**Comment by moylop260** [comment]
I will be happy of have this feature in our docker too:
captura de pantalla 2015-07-30 a las 4 13 42 p m

Notice name of branch in termial shell.

**Comment by ruiztulio** [comment]
I'm working on that, but had some issues with: ```export PS1='\w$(__git_ps1 " (%s)")\$ '``` because I cannot run:
```
RUN echo export PS1='\w$(__git_ps1 " (%s)")\$ ' >> /home/odoo/.bashrc
```
In the Dockerfile and neither:
```
ENV PS1 '\w$(__git_ps1 " (%s)")\$ '
```
In the env var shows like this:
ENV var

And the prompt does not shows as spected:
prompt

**Pull request merged**
