### PR TITLE
[DUMMY][TEST] Test changes from https://github.com/Vauxoo/maintainer-…

### PR DESCRIPTION
**Pull request by ruiztulio**
…quality-tools/pull/308

### CODE REVIEW

**Comment by ruiztulio** [comment]
@moylop260 We have an issue here, we need coverage >= 5 because we are trying to improve the [coverage report](), but It was failing because [pyyaml does not support python <= 3.5](https://github.com/yaml/pyyaml/commit/a7a97871fce027d8c3da0d96117f5b71536b8244), I made this [PR](https://github.com/Vauxoo/maintainer-quality-tools/pull/308) with the canges we need to fix this, but another error raised in the travis build [line 5120](https://travis-ci.org/Vauxoo/docker-odoo-image/builds/641507535#L5120):

a

And I have no idea why. The changes made to the [ci file](https://git.vauxoo.com/vauxoo/instance/commit/1e80d5f2bf9d08b155a3f122100715387020d46d) only works if python >= 3.5, and I'd like to have those for all python versions we use (I guess it doesn't matter for Odoo 8.0 since it is deprecated, but we still need to have coverage and the image built).

Can you help me here?

\cc @nhomar

**Comment by moylop260** [comment]
@ruiztulio 

The following line is using hardcoded version of vim 8.1:
 - https://github.com/Vauxoo/docker-odoo-image/blob/28637f456ba3b205b1071e0079b89cfc059d44e9/odoo-shippable/scripts/build-image.sh#L247

But now looks like is 8.2:
 - https://github.com/Vauxoo/docker-odoo-image/blob/28637f456ba3b205b1071e0079b89cfc059d44e9/odoo-shippable/scripts/build-image.sh#L247

**Comment by moylop260** [comment]
FYI I just fixed hardcoding the new path version:
 - https://github.com/Vauxoo/docker-odoo-image/pull/365

**Comment by moylop260** [comment]
Using https://github.com/Vauxoo/docker-odoo-image/pull/365 and this 364 pr the build is green:

 - https://travis-ci.org/Vauxoo/docker-odoo-image/builds/641924117?utm_medium=notification&utm_source=github_status

I will rebase your branch

**Pull request closed without merging**
