### PR TITLE
[REF] odoo-shippable: Enable git status prompt on-demand

### PR DESCRIPTION
**Pull request by moylop260**
Use `export GIT_STATUS=1` to enable.
Use `unset GIT_STATUS` to disable.

### CODE REVIEW

**Comment by moylop260** [comment]
This PR fix follow issue: https://github.com/Vauxoo/docker-odoo-image/issues/93

Use directly in term `export GIT_STATUS=1` to enable.
Use directly in term `unset GIT_STATUS` to disable.
If you want enabled even then use: `t2d... --run-extra-args="...-e GIT_STATUS=1..."`

@zaoral @JulioSerna @osvalr @gomezvillegasdaniel @KarenKawaii @gmlp 
Feedback please

**Comment by zaoral** [comment]
Im a agree.
Thanks for the contribution @moylop260  +1

**Comment by osvalr** [comment]
:+1:
btw, @moylop260 later on I'll be proposing something like that for zsh

**Comment by KarenKawaii** [comment]
:+1:

**Comment by gomezvillegasdaniel** [comment]
:+1:

**Pull request merged**
