### PR TITLE
[REF] odoo-shippable: Fix vim spf13

### PR DESCRIPTION
**Pull request by moylop260**
-  Fix comments hidden
 - Enable to vim feature to select 
 - Disable mouse functionallity (scroll and click to set position cursor)

### CODE REVIEW

**Comment by moylop260** [comment]
@JulioSerna @KarenKawaii @zaoral @hugho-ad 
Are you right with this change in docker base image?

**Comment by JulioSerna** [comment]
Enable to vim feature to select
:+1:

**Comment by moylop260** [comment]
cc @hbto

**Comment by zaoral** [comment]
thank you @moylop260 +1

**Comment by moylop260** [comment]
cc @suniagajose @josemoralesp 

FYI @josemoralesp me pasó el tip

**Comment by suniagajose** [comment]
good! @moylop260 

thxs

**Pull request merged**
