### PR TITLE
[REF] odoo80: install nodejs to use npm commands

### PR DESCRIPTION
**Pull request by moylop260**

### CODE REVIEW

**Comment by moylop260** [comment]
@nhomar and @ruiztulio 
Can you give me your plus one, please?

**Comment by nhomar** [comment]
+1

**Comment by moylop260** [comment]
@ruiztulio 
Can you give us your feedback here, please?

**Comment by ruiztulio** [comment]
@moylop260 as I asked you by chat, the main idea of installing nodejs isn't installing less?
Like we did in yoytec dockerfile

https://github.com/Vauxoo/yoytec/blob/8.0/deployment_files/docker/Dockerfile#L7-L10

**Comment by moylop260** [comment]
@nhomar 
Do we need install less in all 8.0 instance of odoo?

**Comment by moylop260** [comment]
@nhomar,
Can you help with your reply, please?

**Comment by moylop260** [comment]
Fixed in https://github.com/Vauxoo/docker-odoo-image/pull/21

**Pull request closed without merging**
