### PR TITLE
[WIP] Fixing travis_wait

### LINKED ISSUE #136: Odoo-shippable: travis_wait script is missing
If you add
`travis_wait travis_run_tests` in your script section of .travis.yml now it doesn't works.

Thanks @hbto

### PR DESCRIPTION
**Pull request by LuisAlejandro**
This PR closes #136

### CODE REVIEW

**Comment by LuisAlejandro** [comment]
This is ready for review @moylop260 @ruiztulio.

**Comment by moylop260** [comment]
Could you take advantage of this pr to add compatibility with `travis_wait 23 /entrypoint.sh`?
It 23 is the time to wait but we can ignore it.
Currently this script is compatible just with `travis_wait /entrypoint.sh`

**Comment by LuisAlejandro** [comment]
Oh, ok, i didn't understand. Cool, I'll implement it soon.

**Comment by moylop260** [comment]
@LuisAlejandro I merged this one in order to avoid errors for developers
I'll hope the change of params in other PR

**Comment by LuisAlejandro** [comment]
@moylop260 Yes, thanks. I hope i can do it tomorrow.

**Comment by moylop260** [comment]
@LuisAlejandro 
Do you have any news?

**Comment by LuisAlejandro** [comment]
Sorry, no @moylop260. Tomorrow i'll give it a look.

**Pull request merged**
