### PR TITLE
Fix Dockerfiles contents

### PR DESCRIPTION
**Pull request by osvalr**
The purpose is fix/clean some issues with contents in all Dockerfiles contained in this repo

### CODE REVIEW

**Comment by osvalr** [comment]
@ruiztulio @moylop260 why **```sudo```** is needed [here](https://github.com/vauxoo-dev/docker-odoo-image/blob/75c7798a884a8eb8cc5994bc9bdc4707fc03a0f6/odoo-shippable/Dockerfile#L13) for ```odoo-shippable/Dockerfile``` and the rest of sentences? The same applies to ```odoo80/Dockerfile```

**Comment by moylop260** [comment]
Ok, reading "why copy is better"
http://docs.docker.com/engine/articles/dockerfile_best-practices/#add-or-copy
Thank you @osvalr 

`sudo` is not required if we are using `USER root` (default user)
IMHO you can remove it

@ruiztulio 
What do you think?

**Comment by ruiztulio** [comment]
@moylop260 @osvalr Actually sudo is not required here, the actual user at that point is root, the last user in the base image is root (you can check it [here](https://github.com/vauxoo-dev/docker-odoo-image/blob/75c7798a884a8eb8cc5994bc9bdc4707fc03a0f6/odoo80/Dockerfile)) and as the user haven't change since that moment it remains the same. As an example [here](https://github.com/Vauxoo/docker-odoo-instance/blob/master/test80/Dockerfile#L3) is used the same base image and a new user is added.

**Comment by ruiztulio** [comment]
About the COPY and ADD sounds like they implemented a feature that is not recommended to be used...as most of the time is just copy the file we can change it gradually (all at once seems a little risky for me)

**Comment by osvalr** [comment]
Hi @ruiztulio unless Dockerfiles needs to descompress tarballs magically be added to container filesystem then ADD is the way to go, but in counter case COPY seems to do just what it's needed, and I agree for those ones to be changed (like you said) gradually.

**Comment by osvalr** [comment]
The following document is kind of TL;DR-one but please review in __Too Much Magic__ and __Like ADD, But Less__ sections in https://labs.ctl.io/dockerfile-add-vs-copy/

**Comment by moylop260** [comment]
@ruiztulio 
We can merge it?

**Comment by ruiztulio** [comment]
:+1:

**Comment by moylop260** [comment]
Thanks @osvalr

**Pull request merged**
