### PR TITLE
Add requiremnt file in vauxoo/odoo-80-image

### PR DESCRIPTION
**Pull request by mapuerta**
This PR add requirements file into image odoo80

### CODE REVIEW

**Comment by mapuerta** [comment]
@ruiztulio Ready for review

Download all dependencies python for version 8.0 with this [script](https://gist.github.com/mapuerta/36bd4870696fda73d8b46b973406a24a)
exec_script_download

I tested the changes in the image with this [script](https://gist.github.com/mapuerta/a07bd951c63959acb0cc1dc4fe1cccf5)
test_check_depends

I also tried creating a deployv build for the Yoytec repository and installing the yoytec app, Using this [script](https://gist.github.com/mapuerta/c7ac4a570f103212cd8063ed70d6c757)

test_deployv

build_install_log

**Comment by ruiztulio** [comment]
@mapuerta which instances you take those dependencies from? Also as disscussed before remember to remove all duplicated dependencies from odoo-shippable image if there is any.

**Comment by mapuerta** [comment]
@ruiztulio The dependencies I got them running this [script](https://gist.github.com/mapuerta/36bd4870696fda73d8b46b973406a24a). Search all requirements files in repositories with version 8.0

Removed all duplicate dependencies in the odoo-shippable image
deleted_pips

**Comment by ruiztulio** [comment]
@mapuerta thanks, also can you put thisese fixed versions in the full requirements for 10.0:

```
Pillow==3.4.1
fdb==1.7
lxml==3.5.0
sqlalchemy==1.1.9
xlrd==1.0.0
```

They are required by Odoo 10.0 and are iunstalled everytime we do a build because we use the latest versions instead of the ones required by Odoo, is just takes a minute, but is a minute we can save during the tests and build process.

**Comment by mapuerta** [comment]
@ruiztulio Ready for review

I tried running this [script](https://gist.github.com/mapuerta/a07bd951c63959acb0cc1dc4fe1cccf5)

>  python test_check_depens.py --version 10.0 --branch master-vx-add-files-8.0-requirements-mapuerta --remote vauxoo-dev --build --rm

installed_deps

**Comment by ruiztulio** [comment]
@moylop260 what do you think about these changes?

**Pull request merged**
