### PR TITLE
[IMP] Update Git Version on Dockerfile

### PR DESCRIPTION
**Pull request by lescobarvx**
[IMP] Update Git Version on Dockerfile
https://github.com/Vauxoo/docker-odoo-image/issues/85

### CODE REVIEW

**Comment by moylop260** [comment]
FYI screen shot 2016-03-10 at 1 59 52 pm

**Comment by moylop260** [comment]
@lescobarvx 
Could you add a print-screen with `git --version` to see the new 2.7.X

**Comment by lescobarvx** [comment]
version_git

**Comment by moylop260** [comment]
I will add your layer to `Install depends` layer... to avoid create many layers again.

**Pull request merged**
