### PR TITLE
[FIX] Allow all pip build deps installed so there are no more failing builds

### PR DESCRIPTION
**Pull request by ruiztulio**
With this we hope to avoid errors at build time like the one generated in vauxoo/docker-ubuntu-base#17.

In my local still failing with #122

### CODE REVIEW

**Comment by moylop260** [comment]
:+1: 
This pr fix https://github.com/Vauxoo/docker-odoo-image/issues/123 too
Thanks

**Comment by moylop260** [comment]
@ruiztulio Could you review the log from travis?
https://travis-ci.org/Vauxoo/docker-odoo-image/builds/131799576#L3266-L3274

**Comment by ruiztulio** [comment]
Yeah, I was checking it I'm quite sure it will be solved with this, because I installed all of this dependencies:

deps

And the worked fine, but to test it we must build the odoo80 image and then the shippable one (after this pr is merged)

**Comment by ruiztulio** [comment]
@moylop260 I'm waiting for the base image to build then I'll merge this so the final image have both changes:

build

**Comment by moylop260** [comment]
Thanks!

**Comment by ruiztulio** [comment]
With the 2851fcd and 7649639 I intend to fix #122 and the odoo80 image has no errors in [travis](https://travis-ci.org/Vauxoo/docker-odoo-image/builds/131827157#L1346)

**Pull request merged**
