### PR TITLE
[FIX] odoo110: Using wkhtmltopdf 0.12.5-1 recommended by Odoo

### PR DESCRIPTION
**Pull request by moylop260**
More info about: [0.12.5-1: recommended for Odoo 10 and later.](https://github.com/odoo/odoo/wiki/Wkhtmltopdf)

### CODE REVIEW

**Comment by luisg123v** [comment]
@moylop260 isn't the installed version specified in MQT [here](https://github.com/Vauxoo/maintainer-quality-tools/blob/master/travis/travis_install_nightly#L240) anyway?

**Comment by moylop260** [comment]
For record, I'm reproducing the current red status because of:
 - https://github.com/pypa/pip/issues/5271

It is reproduced using:
 - `python3.5 -m pip install git+https://github.com/vauxoo/server-tools@11.0`


```txt
root@4783e7a35fa9:/# python3.5 -m pip install git+https://github.com/vauxoo/server-tools@11.0
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Collecting git+https://github.com/vauxoo/server-tools@11.0
  Cloning https://github.com/vauxoo/server-tools (to revision 11.0) to /tmp/pip-req-build-ayb1qxc8
  Running command git clone -q https://github.com/vauxoo/server-tools /tmp/pip-req-build-ayb1qxc8
  Running command git checkout -b 11.0 --track origin/11.0
  Switched to a new branch '11.0'
  Branch 11.0 set up to track remote branch 11.0 from origin.
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.5 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ayb1qxc8/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ayb1qxc8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-0228vorw
         cwd: /tmp/pip-req-build-ayb1qxc8/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.5/tokenize.py", line 454, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-ayb1qxc8/setup.py'
    ----------------------------------------
WARNING: Discarding git+https://github.com/vauxoo/server-tools@11.0. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by belisac** [comment]
Hello @moylop260 

Good to know that the information helps, but I haven't test it functionally, you could have my  +1 and If it works! let me know!   

Thanks in advance!

**Comment by moylop260** [comment]
@ruiztulio 

I just added `echo` command to enable verbose output and running:
 - `bash /usr/share/vx-docker-internal/odoo110/build-image.sh`

The error is reproduced.

I just set the variable using only one repository:
`ODOO_DEPENDENCIES="git+https://github.com/vauxoo/server-tools@11.0"`

And the output is:

```txt
git clone https://github.com/vauxoo/server-tools --depth 1 -q -b 11.0 /tmp/tmp.TkdnQziNdY/server-tools
git clone --depth -q -b 8.0 /tmp/tmp.TkdnQziNdY/1
fatal: repository '/tmp/tmp.TkdnQziNdY/1' does not exist
```

If I use `ODOO_DEPENDENCIES=""` there is not an error.

Do you have any clue about to fix it?

**Comment by ruiztulio** [comment]
@moylop260 if I have to gues (I haven't tested it yet) the issue is [here](https://github.com/Vauxoo/docker-odoo-image/blob/master/odoo110/scripts/library.sh#L8), when [these lines](https://github.com/Vauxoo/docker-odoo-image/blob/master/odoo110/scripts/library.sh#L84-L89), they parse the oca_dependencies.txt file and they expect the old syntax (url name) and they get only the name instead.

It is not failing in the 12, 13 neither 14 because we removed [this](https://github.com/Vauxoo/docker-odoo-image/blob/master/odoo110/scripts/build-image.sh#L17-L20) because we noticed it took a little more time to calculate the changes than we saved pre-installing them

**Comment by moylop260** [comment]
@ruiztulio 

Thank you!

So, I just fixed removing them too

Could you check if you are agree, please?

**Comment by moylop260** [comment]
I have created the tag to revert using old image before this change if something is wrong:
 - https://hub.docker.com/r/vauxoo/odoo-100-image/tags
 - https://hub.docker.com/r/vauxoo/odoo-110-image/tags

I have sent the email called: `wkhtmltopdf actualizada a 0.12.5-1 (antes 0.12.4) para odoo 10.0 y 11.0`

So, I merged

**Pull request merged**
