### PR TITLE
[FIX] odoo-shippable: Adding configuration over the file /etc/ssh/sshd_config

### PR DESCRIPTION
**Pull request by JesusZapata**
To avoid the ssh disconnect when the console is inactive in this web page https://www.bjornjohansen.no/ssh-timeout has more information about this trouble

### CODE REVIEW

**Comment by JesusZapata** [comment]
@moylop260 
In this pull request following the instruction on this web page https://www.bjornjohansen.no/ssh-timeout now the ssh server keep alive the connection for `24 hours`

@luisg123v Do you approve this change?

This change avoid the local configuration in `/etc/ssh/sshd_config`

**Comment by luisg123v** [comment]
@JesusZapata 
Since you're setting up this server-side, you should use the config file `sshd_config`, not `ssh_config`

I'm currently testing this, with and without those lines.

**Comment by JesusZapata** [comment]
@luisg123v 
Good review!

**Comment by ruiztulio** [comment]
@JesusZapata who needs to have an *inactive* session open for 24 hours? I understand thet sometimes people go to eat and they don't want to close all and open it when they are back (myself included), but 24 hours? I think 6 hours would be good, if you are afk for more than 6 hours then you don't need to have the session open, at least that's what I think

**Comment by luisg123v** [comment]
@ruiztulio 
You're probably right. However, take into account the following:
- By default, connections are intended to last forever. In this case, connections get dropped most likely because of router/load balancer issues. Actually, if a program like tmux is being used, the connection could last more than 24 hours
- Sometimes, tests could last so much, e.g. when working on modifications to the docker shippable image.

@JesusZapata 
I tested this solution and I can confirm it works as expected. I ran two Docker containers, one with this solution and one without it; only the last one got dropped.

**Comment by luisg123v** [comment]
Anyway, this would be a default value, so 6 hours should be more than enough IMO. If someone, for some reason, needs this value to be greater, it could be changed for that specific container.

**Comment by JesusZapata** [comment]
@ruiztulio @luisg123v 
Done, The time to keep the ssh connection open is `6` hours

**Comment by luisg123v** [comment]
@JesusZapata 
Great! I also noticed you changed `ClientAliveInterval` from `120` to `60`. I like that, it results in a more robust solution.

**Comment by moylop260** [comment]
@ruiztulio could you merge it if LGTY?

**Pull request merged**
