### PR TITLE
[FIX] odoo-shippable: Split rvm gpg command into 2

### PR DESCRIPTION
**Pull request by moylop260**
Using just one there is an error but is silent, now I just added echo
commands

### CODE REVIEW

**Comment by moylop260** [comment]
@luisg123v 
Could you use curl with attempts?
Or download the signature file and adding it to github VCS?

**Comment by moylop260** [comment]
I agree trying download several times like the first option.
If there is not fixed after that then uses the second option for now, if the delay is fixed in the future then we can revert it

The delay is currently affecting us because we can't generate a correct build from the last release:
 - screen shot 2018-07-19 at 10 08 04

**Comment by luisg123v** [comment]
Roger, I'll do it that way.

**Comment by luisg123v** [comment]
@moylop260  
This is ready for review.

I fixed two more issues:
- When Python3.7 is installed, some variables are set, amon which is `$GNUPGHOME`. That variable was pointing to a non-existent directory in `/tmp`. Actually, I think that was the main reason this was failing, because, even if the RVM server was up, it would fail when trying to read config files from that non-existent directory.
- When you split the command to install RVM, you used:  
  `/bin/bash -s stable --ruby /tmp/rvm-installer`  
  but bash expects commands on stdin when it gets the `-s` flag, unless `-c` is provided, so I replaced that line by:  
  `bash /tmp/rvm-installer stable --ruby`

FYI I already tested it and it worked. The only issue I had was I was printing all removed files at the end, and the log got too large ([log](https://travis-ci.org/Vauxoo/docker-odoo-image/builds/406010339?utm_source=github_status&utm_medium=notification)). Now it should work, because I leaved the cleaning-up step as it was.

**Comment by luisg123v** [comment]
@moylop260  
FYI this is finally green!

**Comment by moylop260** [comment]
Good catch!
Thank you
Finally green! 💚

**Pull request merged**
