### PR TITLE
[FIX] Change depth of 10 to 1 on git clone of odoo repo

### PR DESCRIPTION
**Pull request by JesusZapata**
Change depth of 10 to 1 on git clone of odoo repo

### CODE REVIEW

**Comment by JesusZapata** [comment]
@moylop260 
We could save considerable time by lowering the depth of the clone

**Comment by JesusZapata** [comment]
@ruiztulio @moylop260 
What impact would lower the depth of the clone of odoo

**Comment by moylop260** [comment]
The docker hub dont have timeout problem fot this matter.
And this build spent 41 minutes similar to 41 minutes of stable branch build.

Travis build all images even.
Then we need detect what is the folder changed to build just that image and reduce the time of a job.
Similar to mqt to detect changes from pylint_test

**Comment by JesusZapata** [comment]
Sorry for openen this PR but i consider what the parameter `--depth=10` is unnecessary 
We can save time and storage if only changed `--depth=10` for `--depth=1`

I show my server load when clone is `--depth=10` 
image

The command `git --git-dir="${REPO_REQUIREMENTS}/odoo/.git" gc --aggressive` used very CPU

**Comment by JesusZapata** [comment]
I will close this PR because when made push of one branch and this branch only have one commit on depth, the git show error `"Unable to push new commit from shallow clone"`

**Pull request closed without merging**
